package msit_5214;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * 
 * Example 1:
 * 
 * Input: s = "abcd", t = "abcde" Output: "e" Explanation: 'e' is the letter
 * that was added.
 * 
 * Example 2:
 * 
 * Input: s = "", t = "y" Output: "y"
 * 
 * 
 */
public class EasyFindTheDiff {
	public char findTheDifference(String s, String t) {
		// the idea is the same, array with 26 cells and count of easy letter. return this 
		// another one is to use map and counter.
		Map<Character, Integer> holder = new HashMap<>();	
		holder = countChars(s, holder);
		holder = countChars(t, holder);
		
		for(Character ch : holder.keySet()) {
			if(holder.get(ch) == 1) {
				return ch;
			}
		}
		
		return 'N';
	}
	
	Map<Character, Integer> countChars(String s, Map<Character, Integer> holder) {
		for(char ch : s.toCharArray()) {
			if(!holder.containsKey(ch)) {
				holder.put(ch, 1);
			} else {
				holder.merge(ch, 1, Integer::sum);
			}
		}
		return holder;
	}

	public static void main(String[] args) {
		EasyFindTheDiff runner = new EasyFindTheDiff();
		String s = "", t = "y";		
		System.out.println(runner.findTheDifference(s, t));

	}

}
